// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   
     public static final class DriveConstants {
       public static final int kLeftMotor1Port = 2;
       public static final int kLeftMotor2Port = 4;
       public static final int kRightMotor1Port = 3;
       public static final int kRightMotor2Port = 6;
       public static final int karmoter = 1;
       public static final int kwristmoter = 5;
     }
    

    public static final class LevelPID {
        public static final double P = 0.08;
        public static final double I = 0.0;
        public static final double D = 0.0;
        public static final double f = 0.0;
        public static final double LevelTolerance = 0.5; // Measured in degrees
        public static final double Level = 1;
    }

    public static final class MovePID {
        public static final double P = 1.0;
        public static final double I = 0.0;
        public static final double D = 0.0;
        public static final double f = 0.0;
        public static final double MaxAlignSpeed = 2; // Inches per second
        public static final double AlignTolerance = 0.01; // Meters
    }

    public static final class ArmPID {
        public static final double P = .3;
        public static final double I = 0;
        public static final double D = 0;
        public static final double FF = 0;
        public static final double MaxOutput = .8;
        public static final double MinOutput = -.8;
        public static final float ArmForwardLimit = 90;
        public static final float ArmReverseLimit = 0;
    }

    public static final class WristPID {
        public static final double P = .3;
        public static final double I = 0;
        public static final double D = 0;
        public static final double kFF = 0;
        public static final double MaxOutuput = .7;
        public static final double MinOutuput = -.7;
    }
}

